/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_BE5AF32__
#define __PLUGINEDITOR_H_BE5AF32__

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class KickMakerAudioProcessorEditor  : public AudioProcessorEditor
{
public:
    KickMakerAudioProcessorEditor (KickMakerAudioProcessor* ownerFilter);
    ~KickMakerAudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
};


#endif  // __PLUGINEDITOR_H_BE5AF32__
